import assert from 'node:assert/strict';
import { buildLitz, litzPreset } from '../web/js/engine/litz.js';
import { validateLitz } from '../web/js/engine/litz-validation.js';
import { validateManufacturing } from '../web/js/engine/litz-manufacturing.js';
import { compareLitzBaseline, searchLitzDesigns } from '../web/js/engine/litz-studies.js';
import { exportKicadPcb } from '../web/js/engine/exporters.js';

const cfg = { ...litzPreset(), turns: 2, litzOutline: true };
const geometry = buildLitz(cfg), original = JSON.stringify(cfg);
const comparison = compareLitzBaseline(cfg, geometry, { analyse: false });
assert.equal(comparison.validated, false);
const row = key => comparison.constraints.find(r => r.key === key);
for (const key of ['strands', 'turns', 'width', 'stack', 'copper', 'pitch', 'terminals', 'nominalDiameter']) assert.equal(row(key).matched, true, key);
for (const key of ['actualDiameter', 'actualBore', 'copperVolume', 'vias']) assert.equal(row(key).matched, false, `difference must be explicit: ${key}`);
assert.equal(comparison.reference.metrics.viaCount, 0);
assert.ok(comparison.braid.metrics.Rdc > comparison.reference.metrics.Rdc, 'fanout length and barrels incur a real DC cost');
assert.ok(comparison.braid.metrics.copperVolumeMM3 > comparison.reference.metrics.copperVolumeMM3);
assert.equal(validateLitz(comparison.reference.geometry, comparison.reference.geometry.config).ok, true);
assert.ok(exportKicadPcb(comparison.reference.geometry.art).includes('(kicad_pcb'));
assert.ok(comparison.warnings.some(s => /not.*measured Q/.test(s)));
const ordinary = comparison.ordinary, ordinaryRow = key => ordinary.constraints.find(r => r.key === key);
assert.equal(ordinary.kind, 'conventional-four-layer-parallel');
assert.equal(ordinary.config.layers, 4); assert.equal(ordinary.config.traceW, 4 * cfg.traceW);
assert.equal(ordinaryRow('crossSection').matched, true, 'wide conventional traces match aggregate conductor cross-section');
assert.equal(ordinaryRow('stack').matched, true);
assert.equal(ordinaryRow('branches').matched, false); assert.equal(ordinaryRow('terminals').matched, false);
assert.equal(ordinaryRow('copperVolume').matched, false, 'matching width budget does not mean matching copper volume');
assert.equal(ordinary.geometry.coil.spiral.turnsUsed, cfg.turns, 'ordinary comparison must retain every turn');
assert.deepEqual(ordinary.geometry.layers.map(l => l.z), geometry.layers.map(l => l.z));
const board = exportKicadPcb(ordinary.geometry.art);
assert.ok(board.includes('(thickness 1.58)')); assert.ok(board.includes('(layer "dielectric 2" (type "core") (thickness 0.5))'));
assert.ok(ordinary.warnings.some(s => /cannot be attributed solely/.test(s)));
assert.equal(JSON.stringify(cfg), original, 'comparison must not change the active configuration');
const invalid = structuredClone(geometry); invalid.art.vias.pop();
assert.throws(() => compareLitzBaseline(cfg, invalid, { analyse: false }), /valid copper/);

// A cached 96-subdivision result must not be compared against a 48-subdivision
// reference. Both sides are re-evaluated at the same selected resolution.
const cached = { L: 1, Rac: .1, Q: 10, Zr: .1, Zi: 1, segmentCapUsed: 96 };
const curve = [{ f: 1e6, R: .1, L: 1e-6, Q: 10, Zr: .1, Zi: 1 }];
const modeled = compareLitzBaseline(cfg, geometry, { analysis: cached, curve, count: 3, segmentCap: 48 });
assert.notEqual(modeled.braid.metrics.L, cached.L);
assert.notDeepEqual(modeled.braid.curve, curve);
assert.equal(modeled.braid.curve.length, 3);
assert.equal(modeled.resolution.cachedBraidReused, false);
assert.equal(modeled.braid.metrics.segmentCapUsed, 48);
assert.equal(modeled.reference.metrics.segmentCapUsed, 48);
assert.equal(modeled.braid.metrics.lossSamplesUsed, modeled.reference.metrics.lossSamplesUsed);
assert.ok(modeled.warnings.some(s => /recalculated.*matching model/.test(s)));
assert.equal(modeled.reference.curve.length, 3);
assert.ok(modeled.reference.curve.every(p => Number.isFinite(p.L) && Number.isFinite(p.R)));
assert.equal(modeled.ordinary.curve.length, 3);
assert.ok(modeled.ordinary.curve.every(p => Number.isFinite(p.L) && Number.isFinite(p.R)));
assert.ok(modeled.warnings.some(s => /Intrinsic distributed capacitance and dielectric loss are disabled/.test(s)));
const selectedModels = compareLitzBaseline({ ...cfg, litzCapacitanceMode: 'distributed', litzAcModel: 'rectangular' }, geometry, { analyse: false });
assert.ok(selectedModels.warnings.some(s => /capacitance and dielectric conductance are enabled/.test(s)));
assert.ok(selectedModels.warnings.some(s => /rectangular-filament model resolves/.test(s)));
assert.ok(!selectedModels.warnings.some(s => /distributed capacitance.*outside the model|distributed capacitance and dielectric loss are disabled/.test(s)));

const progress = [];
const found = await searchLitzDesigns({ ...cfg, litzOutline: false }, { maxEvaluations: 3, turns: [2, 3], widths: [.8], pitches: [5.5], stepAngles: [30] }, p => progress.push(p));
assert.equal(found.evaluated, 2); assert.equal(found.candidates.length, 2);
assert.ok(progress.length >= 2);
for (const candidate of found.candidates) {
  assert.ok([2, 3].includes(candidate.config.turns)); assert.equal(candidate.config.traceW, .8);
  assert.equal(candidate.config.litzOutline, true); assert.ok(candidate.issues.some(s => /outline enabled/.test(s)));
  assert.equal(candidate.metrics.L, null); assert.equal(candidate.metrics.Q, null);
  assert.ok(candidate.metrics.boardDiameterMM > candidate.metrics.outerDiameterMM);
  const rebuilt = buildLitz(candidate.config), checked = validateLitz(rebuilt, candidate.config);
  assert.equal(checked.ok, true); assert.equal(validateManufacturing(rebuilt, candidate.config, checked).ok, true);
}
assert.ok(found.candidates[0].score <= found.candidates[1].score);
const limited = await searchLitzDesigns(cfg, { maxEvaluations: 1, turns: [2, 3], widths: [.8], pitches: [5.5], stepAngles: [30], maxVias: 1 });
assert.equal(limited.evaluated, 1); assert.equal(limited.candidates.length, 0); assert.equal(limited.rejected[0].stage, 'physical');
const impossible = await searchLitzDesigns(cfg, { maxEvaluations: 1, turns: [30], widths: [.8], pitches: [5.5], stepAngles: [30] });
assert.equal(impossible.evaluated, 0); assert.ok(impossible.pruned > 0);
const fabRejected = await searchLitzDesigns({ ...cfg, litzFabRules: { minPlating: 60 } }, { maxEvaluations: 1, turns: [2], widths: [.8], pitches: [5.5], stepAngles: [30] });
assert.equal(fabRejected.candidates.length, 0); assert.ok(fabRejected.rejected.some(r => r.issues.some(s => /plating/i.test(s))));
const cancelled = await searchLitzDesigns(cfg, { signal: AbortSignal.abort() });
assert.equal(cancelled.cancelled, true); assert.equal(cancelled.evaluated, 0);
let stop = false;
const afterOne = await searchLitzDesigns(cfg, { maxEvaluations: 3, cancelled: () => stop }, () => { stop = true; });
assert.equal(afterOne.evaluated, 1); assert.equal(afterOne.cancelled, true);
await assert.rejects(() => searchLitzDesigns(cfg, { targetQ: 200 }), /Q optimization is disabled/);
await assert.rejects(() => searchLitzDesigns(cfg, { maxEvaluations: 13 }));
await assert.rejects(() => searchLitzDesigns(cfg, { maxModelEvaluations: 3 }));
const target = await searchLitzDesigns(cfg, { maxEvaluations: 1, maxModelEvaluations: 1, turns: [2], widths: [.8], pitches: [5.5], stepAngles: [30], targetL: 1e-6 });
assert.equal(target.models, 1); assert.equal(target.candidates[0].targetAssessed, true);
assert.ok(Number.isFinite(target.candidates[0].metrics.targetError));
assert.equal(target.candidates[0].metrics.Q, null, 'target-L screening must not become an unvalidated Q search');
console.log('PCB Litz studies passed: explicit reference constraints, independent curves, bounded/cancellable DC and target-L searches, fabricated candidate regeneration, and invalid-budget rejection.');
