"""Refresh the local review page from native CAD exports."""
from pathlib import Path
import json,html,base64
R=Path(__file__).resolve().parents[1]
names=['F_Cu','In1_Cu','In2_Cu','In3_Cu','In4_Cu','In5_Cu','In6_Cu','B_Cu']
roles=['Primary section 1 and top electronics','Secondary A','Parallel secondary A','Routing','Routing','Secondary B','Parallel secondary B','Primary section 2']
views=[{'name':f'L{i+1} · {n.replace("_",".")}','role':roles[i],'src':'data:image/svg+xml;base64,'+base64.b64encode((R/f'evidence/pcb-layers/PS-GAN-60W-{n}.svg').read_bytes()).decode()} for i,n in enumerate(names)]
buttons=''.join(f'<button onclick="selectLayer({i})">{i+1} · {n.replace("_",".")}</button>' for i,n in enumerate(names))
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>PS-GAN-60W · A3 schematic review</title><style>
*{box-sizing:border-box}body{margin:0;background:#f2f3ef;color:#19362f;font:16px/1.6 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:36px 28px}h1{font-size:clamp(36px,6vw,68px);line-height:1.07;letter-spacing:-2px;margin:12px 0}h2{font-size:27px;line-height:1.2}p{max-width:84ch}a{color:#12614e;text-underline-offset:3px}.kicker{font-size:12px;letter-spacing:2px;font-weight:700}.hero{display:grid;grid-template-columns:1fr 1.1fr;gap:28px;align-items:center}.hero img{width:100%;border-radius:16px}.card{background:white;border:1px solid #d4dfd6;border-radius:16px;padding:26px;margin:25px 0}.card img{max-width:100%;height:auto}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin:24px 0}.stat{border-top:2px solid #365f4a;padding:12px 0}.stat strong{display:block;font-size:27px}.stat span{font-size:13px}.links{display:flex;gap:16px;flex-wrap:wrap;margin:18px 0}.tag{display:inline-block;padding:5px 12px;border:1px solid #bb984e;background:#fff4d7;border-radius:18px;font-size:13px}.note{border-left:4px solid #bb984e;padding:8px 18px;background:#fff8e9}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}button{font:inherit;padding:8px 13px;border:1px solid #99b3a4;border-radius:8px;background:white;color:#234a36;cursor:pointer}button.active{background:#234a36;color:white}.tabs{display:flex;gap:8px;flex-wrap:wrap}#layer-image{display:block;max-height:760px;margin:20px auto;background:white}footer{font-size:13px;color:#526b5e}@media(max-width:760px){main{padding:20px 14px}.hero,.grid{grid-template-columns:1fr}.stats{grid-template-columns:1fr 1fr}.card{padding:17px}}
</style></head><body><main>
<header class="hero"><div><div class="kicker">PLANAR STUDIO · A3 SCHEMATIC / A2 HARDWARE · 10 OCTOBER 2026</div><h1>PS-GAN-60W</h1><p>48 V nominal → isolated 12 V / 5 A target. A compact GaN power stage around an integrated PCB transformer.</p><span class="tag">Engineering prototype · unbuilt and untested</span><nav class="links"><a href="Schematic.pdf">Schematic PDF</a><a href="kicad/PS-GAN-60W.kicad_pro">KiCad project</a><a href="README.md">Project guide</a></nav></div><a href="Board-perspective.png"><img src="Board-perspective.png" alt="Native KiCad A2 render with planar core and opposing terminal headers"></a></header>
<div class="stats"><div class="stat"><strong>64 × 56 mm</strong><span>PCB outline bounding size</span></div><div class="stat"><strong>23% less area</strong><span>versus the 80 × 58 mm A1 board</span></div><div class="stat"><strong>8 layers</strong><span>six winding layers · 2 oz target</span></div><div class="stat"><strong>75 top parts</strong><span>73 SMT + two through-hole headers</span></div></div>
<section class="card"><h2>Trace the circuit directly</h2><p>The A3 revision uses aligned reference/value fields, separate capacitor ratings and fewer internal net labels. It separates power conversion, frequency control, local bias, isolated feedback and independent output overvoltage protection. Local connections are wired visibly; matching signal names connect sections. The rendered text-to-wire clearance screen passes with a 0.15 mm reserve. The native four-way-junction check is enabled and passes, with no four-way wire connections in the independent geometry audit.</p><a href="Schematic.pdf"><img src="Schematic-preview.png" alt="A3 schematic with five wired functional groups"></a><div class="links"><a href="evidence/schematic-power.png">Power stage detail</a><a href="evidence/schematic-control.png">Control and bias detail</a><a href="evidence/schematic-feedback.png">Feedback detail</a><a href="evidence/ERC.rpt">ERC report</a></div></section>
<section class="card"><h2>Compact, with bench access</h2><div class="grid"><a href="Board-preview.png"><img src="Board-preview.png" alt="Top view of compact A2 board"></a><div><p>Opposing 5.08 mm headers accept removable screw-terminal plugs. Bench leads can be changed without soldering a harness. Six bare probe pads provide VIN/PGND, VOUT/SGND and V5/AGND measurement pairs.</p><p>Four M3 holes reuse the flyback example's exact exposed-substrate edge footprint: 3.2 mm drill, 6.4 mm mask opening and 10 mm exclusion on all copper layers. The compact board uses a <strong>55 × 47 mm pattern</strong>, different from the flyback's spacing.</p><p>Pin 2 is positive and pin 1 is return on both power ports. Mark the mating input and output plugs: the identical connector family does not prevent a cable swap.</p><p>Headers overhang the PCB. Plugs, wire bend radius, removal space and the underside ferrite add to the assembly envelope. Renders show unmated headers; the area reduction describes the PCB only.</p><div class="links"><a href="mechanical.json">Dimensions</a><a href="PER-DESIGN-STUDY.md">MIT PER study</a><a href="evidence/Board-bottom.png">Underside</a></div></div></div></section>
<section class="card"><h2>Look through the winding stack</h2><p>The 4:2:2 transformer has repeatable PCB windings, paralleled secondary layers and a stock ELP22 core. It needs no bobbin or hand-wound coil. The tradeoffs include eight heavy-copper layers, filled vias, termination loss and coupling/capacitance that still require measurement.</p><div class="tabs">%%BUTTONS%%</div><h3 id="layer-name"></h3><p id="layer-role"></p><img id="layer-image" alt="Selected native KiCad copper layer"><p><a href="PCB-layers.pdf">All layers as PDF</a> · <a href="evidence/winding-contact-audit.json">Winding-contact screen</a></p></section>
<section class="card"><h2>Parts and assembly</h2><p><strong>$23.68 electronics + $0.39 mating plugs + about $6.88 core/clips = $30.95 parts allowance.</strong> Catalog snapshots exclude PCB, assembly, setup, attrition, minimum quantities, tax and shipping.</p><p>The board headers are C3697; two matching C71370 screw plugs are external accessories, not PCB placements. All 75 purchased PCB parts map to 41 stocked catalog codes in the snapshot. L2 has only 39 units in that snapshot.</p><div class="links"><a href="JLCPCB-SOURCING.md">Sourcing and drawings</a><a href="sourcing/Electronics-BOM-review.csv">PCB BOM</a><a href="sourcing/Mating-plugs.csv">Mating plugs</a><a href="sourcing/Core-and-clips.csv">DigiKey core/clip list</a></div><p class="note"><strong>Turnkey acceptance remains open.</strong> JLCPCB must review the files, exact stack, filled/capped vias, placement rotations and through-hole solder process. Its installation of the DigiKey core halves and clips has not been agreed. No order has been placed.</p></section>
<section class="card"><h2>Checked CAD, unqualified hardware</h2><p>ERC, DRC, connectivity, schematic parity, pin-net mapping and BOM/CPL agreement pass. Independent geometry checks screen winding contacts and junctions. A clean-directory rebuild reproduces the routing and pad geometry.</p><p>First-harmonic calculations are a screening model, not a switching simulation. The 60 W target still needs magnetics, startup, no-load behavior, current limit, OVP, ZVS, synchronous rectifier timing, control-loop and thermal validation. Functional isolation only.</p><div class="links"><a href="VALIDATION.md">Validation record</a><a href="evidence/DRC.rpt">DRC</a><a href="evidence/rebuild-audit.json">Rebuild audit</a><a href="manufacturing-prototype/READ-BEFORE-ORDER.txt">Manufacturing notes</a></div></section>
<footer>Native KiCad 10 exports. KiStack workflows used. The MIT PER study is an independent design reference; no affiliation or endorsement is implied. <a href="THIRD-PARTY-NOTICES.txt">Sources and notices</a>.</footer>
<script>
const layers=%%LAYERS%%;
function selectLayer(i){const v=layers[i];document.getElementById('layer-name').textContent=v.name;document.getElementById('layer-role').textContent=v.role;document.getElementById('layer-image').src=v.src;document.querySelectorAll('.tabs button').forEach((b,n)=>{b.classList.toggle('active',n===i);b.setAttribute('aria-pressed',String(n===i));});}
selectLayer(0);
</script></main></body></html>'''
(R/'Review.html').write_text(page.replace('%%BUTTONS%%',buttons).replace('%%LAYERS%%',json.dumps(views)),encoding='utf8')
print('Review page refreshed.')
